### ISSUE TITLE
Error reloading the page with cookies disabled

### ISSUE THREAD

**Issue by frbuceta** [nuxt-community/auth-module#376] opened 2019-06-09 14:33 UTC
### Version

[v4.6.6](https://github.com/auth-module/releases/tag/v4.6.6)

### Steps to reproduce

Set "cookies: false" in nuxt.config.js and within the pages with auth middleware, reload the page and immediately take you to login

### What is expected ?

that does not do that redirection

### What is actually happening?

That the middleware is not working correctly, because the store still has the same data as before doing the redirection

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c354">#c354</a>)</em></sub></div>

**Comment by DannyEndert** [comment] 2019-07-24 10:53
**Hello @frbuceta**,

I had the same problem and for me it was the value "baseUrl" in the "nuxt.config.js". Are you sure that you have specified the correct url there?

Because with the option "resetOnError: true" my login was reset directly.

@maniL Can it be that the documentation "ignoreExceptions" is not described? Because for me it was a "save and test" procedure and after a look into the source code, there seems to be this option.

**Best regards**

Danny Endert

**Comment by bmulholland** [comment] 2022-01-20 10:51
We don't have bandwidth to support v4, so closing this out -- but please let me know if this is still happening with auth-next.

If you're using SSR, though, this is expected behavior: cookies are necessary so that the server knows who the user is during page generation. If there's no cookie, the server will think the user isn't logged in, so of course it will redirect them.

**Closed by bmulholland** 2022-01-20 10:51 UTC
Labels: bug
