### ISSUE TITLE
how to capture authorization token when returned as response header?

### ISSUE THREAD

**Issue by vesper8** [nuxt-community/auth-module#759] opened 2020-07-11 13:46 UTC
I don't see anywhere in the docs on how to handle this scenario. The /api/auth/login endpoint does not return the token in the body but rather as a header.

```
        return response([
            'status' => 'success',
        ])
        ->header('Authorization', $token);
```

How can I instruct the nuxt-auth module to set the authorization token when it is returned in such a way please? Anyone?

**Comment by bmulholland** [comment] 2021-01-26 08:23
Apologies for the slow response here. Can you please share what service returns a token this way?

**Comment by bmulholland** [comment] 2021-01-26 08:52
Ah, looks like this is a dupe of https://github.com/nuxt-community/auth-module/issues/759

**Closed by bmulholland** 2021-01-26 08:52 UTC
Labels: enhancement
