### ISSUE TITLE
Event after successful login with oauth 

### ISSUE THREAD

**Issue by themathmagician** [nuxt-community/auth-module#1157] opened 2021-05-03 21:26 UTC
Hi there
I am trying to figure out, how to get an event after the user has successfully logged in.
I am using AWS Cognito as oauth provider, and it is redirecting to a social login.

I tried to add a listener in created / mounted / fetch of my default layout, but it only gets triggered when the user logs out:
```
this.$auth.$storage.watchState('loggedIn', (newValue) => { console.log(`[loggedIn-created] change, new value: ${newValue}`) })
```
So, my question is, where should I register, to receive an event when the user logs in?
I need to call my api, to load the user profile after login.

**Comment by bmulholland** [comment] 2022-01-24 10:57
Dupe of https://github.com/nuxt-community/auth-module/discussions/1595

**Closed by bmulholland** 2022-01-24 10:57 UTC
Labels: question
