### ISSUE TITLE
Option to not send code_challenge_method for oauth2 schemes

### ISSUE THREAD

**Issue by VesterDe** [nuxt-community/auth-module#850] opened 2020-10-07 21:07 UTC
Google does not allow `code_challenge_method` as a param for its oauth scheme, and errors if it receives it.

![image](https://user-images.githubusercontent.com/722505/95387744-764f9680-08f1-11eb-9c6d-dbab59ae17df.png)

If I understand the source code correctly, there is currently no way to not send it?

That means Google Oauth is unusable for now?

Happy to be shown where I'm not doing something right. Otherwise I'm happy to add a `delete` statement somewhere in the right area.

My provider setup is:

```
      google: {
        endpoints: {
          userInfo: '/api/auth/user',
          logout: { url: '/api/auth/logout', method: 'get', withCredentials: true },
        },
        redirectUri: `${FULL_URL}/api/oauth/google/callback`,
        clientId: process.env.GOOGLE_CLIENT_ID,
      },
```

**Comment by p3t3r67x0** [comment] 2020-10-22 10:39
Unfortunately I had experienced the same on my end. Which version of @nuxtjs/auth or @nuxtjs/auth-next do you use?

**Comment by VesterDe** [comment] 2020-10-22 11:42
@p3t3r67x0 @nuxt/auth-next latest.

**Comment by p3t3r67x0** [comment] 2020-10-22 12:07
@VesterDe it seems when setting `codeChallengeMethod` to an empty string it works, did you tried that?

```javascript
auth: {
  strategies: {
    google: {
      responseType: 'code',
      codeChallengeMethod: '',
      grantType: 'authorization_code',
      clientSecret: process.env.CLIENT_SECRET,
      clientId: process.env.CLIENT_ID
    }
  }
}
```

**Comment by bmulholland** [comment] 2020-10-22 15:08
I'm also using auth-next and have Google working fine. These are the options I have set:

```
        responseType: 'code',
        accessType: 'offline',
        grantType: 'authorization_code',
        codeChallengeMethod: 'S256'
```

**Comment by VesterDe** [comment] 2020-11-03 20:09
Thanks for the input, I'm going to try and figure out what I'm doing wrong. I'll close the issue if I do.

**Comment by vinayakkulkarni** [comment] 2020-11-08 17:46
Anyone with a reproducible repo?

**Comment by clorichel** [comment] 2020-11-15 08:43
Just hit the same issue with latest nuxt and `@nuxtjs/auth-next`. Adding `codeChallengeMethod: '',` made it work:

```
auth: {
    strategies: {
      google: {
        clientId: process.env.GOOGLE_CLIENT_ID,
        codeChallengeMethod: '',
      },
    },
  },
```

Thanks p3t3r67x0 ❤️

This issue did not happen for me with `@nuxtjs/auth`.

---

@vinayakkulkarni here is how to reproduce:
- default `npx create-nuxt-app`
- add `@nuxtjs/auth-next`, enable it in nuxt.config.js `router: { middleware: ['auth'] },` and use the snippet above without `codeChallengeMethod`
- you got Google complaining like in the screenshot of this issue
- add `codeChallengeMethod: ''` and it works again 🤓 

Just in case some nuxt config has an impact (which I doubt, but who knows), here is mine:

```
create-nuxt-app v3.4.0

    Programming language: TypeScript
    Package manager: Yarn
    UI framework: Tailwind CSS
    Nuxt.js modules: Axios
    Linting tools: ESLint, Prettier, StyleLint
    Testing framework: Jest
    Rendering mode: Universal (SSR / SSG)
    Deployment target: Static (Static/JAMStack hosting)
    Development tools: None
    Continuous integration: None
    Version control system: Git
```

**Comment by vinayakkulkarni** [comment] 2020-11-17 07:44
@clorichel : Thanks for the revert. I actually managed to solve it using old `@nuxtjs/auth` module itself!

https://github.com/vinayakkulkarni/map-my-google-photos/blob/main/nuxt.config.ts#L111-L128

The thing is, `@nuxtjs/auth` uses snake case (`_`) whereas, the new `@nuxtjs/auth-next` uses camelCasing. 

There'll probably be a migration guide when new major version is released of `@nuxtjs/auth` :)

**Comment by bmulholland** [comment] 2020-12-08 11:56
@clorichel Did you try with `codeChallengeMethod: 'S256'`? It seems like leaving that blank might use a less secure challenge method.

**Comment by clorichel** [comment] 2020-12-08 13:59
No I didn't @bmulholland. Seems like a good point though: would you have any documentation link for me to know more about what Google is implementing on their end and what it actually stands for in term of security? 🤓

**Comment by bmulholland** [comment] 2020-12-08 14:04
@clorichel Anything on Google's end is up to them to document, so you'll have to check on that side :)

**Comment by bmulholland** [comment] 2020-12-08 14:08
My recommendation is to use the config I posted above, including the S256 option. I've created https://github.com/nuxt-community/auth-module/issues/908 to improve the code and/or docs. For this specific request, if you really want to avoid it, the workaround of a blank string seems to provide the option to not send that parameter. Let me know if I've missed anything, but closing this out for now.

**Closed by bmulholland** 2020-12-08 14:08 UTC

**Comment by goldengecko** [comment] 2021-04-03 03:45
I'm having trouble using the auth code I get back to exchange for a token from Google. I'm using config:
```javascript
      google: {
        clientId: process.env.GOOGLE_OAUTH_CLIENT_ID,
        codeChallengeMethod: 'S256', // Required because the default causes google to throw invalid request
        responseType: 'code', // Required because the default 'token' includes rejected nonce arg
        accessType: 'offline', // Required to ensure we get a long lived refresh token
        grantType: 'authorization_code',
        endpoints: {
          token: '/api/v1/auth/google-code',
        },
      },
```
This seems to be working, and my google-code api is getting called with a payload that includes: code, client_id, redirect_uri, response_type, audience (an empty string), grant_type, and code_verifier.

I understand that I need to use this to ask Google for a token, so I post to `https://oauth2.googleapis.com/token` with a payload that includes: code, client_id, client_secret, redirect_uri and grant_type (authorization_code). Google just responds with a 400 error which it says is an "invalid_grant" and "bad request".

Could this be because of something in the auth system not requesting the authentication correctly, or am I calling Google incorrectly.

**Comment by TranBaVinhSon** [comment] 2021-04-10 16:21
Same problem with @goldengecko 👍

**Comment by kekhuay** [comment] 2021-05-01 13:01
i have this same problem with AWS Cognito as well and set `codeChallengeMethod` to empty string does not help either. i think this parameter should not be sent by default or at least has an option to exclude it.

**Comment by joergbs** [comment] 2021-05-21 14:41
With AWS Cognito I tested the following scenarios:

### Implicit grant
**Result**: Works
**Comment**: but in this case refresh tokens are not supported by AWS Cognito.
**Configuration**:
```
  auth: {
    strategies: {
      awscognito: {
        scheme: 'oauth2',
        endpoints: {
          authorization: 'https://xxxxxxxxxx.auth.us-east-1.amazoncognito.com/oauth2/authorize',
          token: 'https://xxxxxxxxxx.auth.us-east-1.amazoncognito.com/oauth2/token',
          userInfo: 'https://xxxxxxxxxx.auth.us-east-1.amazoncognito.com/oauth2/userInfo',
          logout: 'https://xxxxxxxxxx.auth.us-east-1.amazoncognito.com/logout'
        },
        token: {
          property: 'access_token',
          type: 'Bearer',
          maxAge: 1800
        },
        refreshToken: {
          property: 'refresh_token',
          maxAge: 60 * 60 * 24 * 30
        },
        responseType: 'token',
        accessType: undefined,
        redirectUri: 'http://localhost:3000/login',
        logoutRedirectUri: 'http://localhost:3000/login',
        clientId: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        scope: ['openid', 'profile', 'email'],
        state: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        codeChallengeMethod: 'S256',
        responseMode: '',
        acrValues: '',
        // autoLogout: false
      }
    }
  }
```
### Authorization code grant (with empty codeChallengeMethod):
**Result**: Does not work. 
**Comments**: AWS Cognito does not like when 'code_challenge_method' is empty. But when I re-execute the same get request with cURL without code_challenge_method, then it is successful.
**Configuration**:
```
  auth: {
    strategies: {
      awscognito: {
        scheme: 'oauth2',
        endpoints: {
          authorization: 'https://xxxxxxxxxx.auth.us-east-1.amazoncognito.com/oauth2/authorize',
          token: 'https://xxxxxxxxxx.auth.us-east-1.amazoncognito.com/oauth2/token',
          userInfo: 'https://xxxxxxxxxx.auth.us-east-1.amazoncognito.com/oauth2/userInfo',
          logout: 'https://xxxxxxxxxx.auth.us-east-1.amazoncognito.com/logout'
        },
        token: {
          property: 'access_token',
          type: 'Bearer',
          maxAge: 1800
        },
        refreshToken: {
          property: 'refresh_token',
          maxAge: 60 * 60 * 24 * 30
        },
        responseType: 'code',
        grantType: 'authorization_code',
        accessType: undefined,
        redirectUri: 'http://localhost:3000/login',
        logoutRedirectUri: 'http://localhost:3000/login',
        clientId: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        scope: ['openid', 'profile', 'email'],
        state: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        codeChallengeMethod: '',
        responseMode: '',
        acrValues: '',
        // autoLogout: false
      }
    }
  }
```

### Authorization code grant (with codeChallengeMethod = S256):
**Result**: Does not work.
**Comments**: The request to the authorization endpoint works, but the request to the token endpoint fails with HTTP 400 (invalid client).
**Configuration**:
```
  auth: {
    strategies: {
      awscognito: {
        scheme: 'oauth2',
        endpoints: {
          authorization: 'https://xxxxxxxxxx.auth.us-east-1.amazoncognito.com/oauth2/authorize',
          token: 'https://xxxxxxxxxx.auth.us-east-1.amazoncognito.com/oauth2/token',
          userInfo: 'https://xxxxxxxxxx.auth.us-east-1.amazoncognito.com/oauth2/userInfo',
          logout: 'https://xxxxxxxxxx.auth.us-east-1.amazoncognito.com/logout'
        },
        token: {
          property: 'access_token',
          type: 'Bearer',
          maxAge: 1800
        },
        refreshToken: {
          property: 'refresh_token',
          maxAge: 60 * 60 * 24 * 30
        },
        responseType: 'code',
        grantType: 'authorization_code',
        accessType: undefined,
        redirectUri: 'http://localhost:3000/login',
        logoutRedirectUri: 'http://localhost:3000/login',
        clientId: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        scope: ['openid', 'profile', 'email'],
        state: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        codeChallengeMethod: 'S256',
        responseMode: '',
        acrValues: '',
        // autoLogout: false
      }
    }
  }
```

based on that I believe there are two issues:
1. there need to be an extra option to control whether or not to send the code_challenge_method parameter. Or, alternativly, simply do not send the code_challenge_method parameter, when option codeChallengeMethod is an empty string.
2. if the codeChallengeMethod option is set to S256, then either auth or cognito verify differently (not sure which one is wrong).

**Comment by goldengecko** [comment] 2021-05-31 10:26
@TranBaVinhSon I have found the solution for this and have updated my post

**Comment by brhanegiday** [comment] 2022-10-06 09:12
I had a similar issue. Now I fixed it by setting the **response_type** value to **_code_**. See the image below:

```
GoogleProvider({
    clientId: process.env.GOOGLE_CLIENT_ID,
    clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    authorization: {
      params: {
        prompt: 'consent',
        response_type: 'code',
        scope: 'openid profile email',
        redirect_uri: process.env.GOOGLE_REDIRECT_URI_LOCAL,
        include_granted_scopes: true,
      },
    },
  }),


```
