### ISSUE TITLE
LaravelJWT error with ExpiredAuthSessionError: Both token and refresh token have expired. Your request was aborted.

### ISSUE THREAD

**Issue by oommgg** [nuxt-community/auth-module#945] opened 2020-12-18 14:25 UTC
"@nuxtjs/auth-next": "5.0.0-1608280312.c5867c3"
"nuxt": "^2.14.12",

```js
  auth: {
    strategies: {
      laravelJWT: {
        provider: 'laravel/jwt',
        url: '/api/auth',
        endpoints: {
          login: { url: '/api/auth/login', method: 'post' },
          refresh: { url: '/api/auth/refresh', method: 'post' },
          user: { url: '/api/auth/user', method: 'get' },
          logout: { url: '/api/auth/logout', method: 'post' },
        },
        token: {
          property: 'token',
          maxAge: 60 * 60,
        },
        refreshToken: {
          property: 'token',
          maxAge: 20160 * 60,
        },
        user: {
          property: 'user',
        },
      },
    },
  },
  axios: {
    proxy: true,
    credentials: true,
  },
  proxy: {
    '/api': {
      target: process.env.API_URL || process.env.APP_URL,
    },
  },
  router: {
    middleware: ['auth'],
  },
```

1. When logged in, then do "logout", and refresh page got:

    ExpiredAuthSessionError: Both token and refresh token have expired. Your request was aborted.
    at eval (webpack-internal:///./node_modules/@nuxtjs/auth-next/dist/runtime.mjs:798:17)

2. clean all cookie from chrome, refresh page got same problem

    ExpiredAuthSessionError: Both token and refresh token have expired. Your request was aborted.
    at eval (webpack-internal:///./node_modules/@nuxtjs/auth-next/dist/runtime.mjs:798:17)

**Comment by dz0tto** [comment] 2020-12-18 15:19
Same bug appeared with local stategy today, and it worked just fine before.

**Comment by ximzavivka** [comment] 2020-12-18 15:44
Looks like dev team dont need to check token and token validity for each request because i actually have mane requests which is not requirs any tokens
```js
 const token = this.scheme.token.get();
      if (!isValid) {
        if (!token && this._requestHasAuthorizationHeader(config)) {
          throw new ExpiredAuthSessionError();
        }
        return config;
      }
```

**Comment by steklopod** [comment] 2020-12-18 15:47
Same bug, downgrade to `"@nuxtjs/auth-next": "5.0.0-1607693598.34d83ea"` fix my problem

**Comment by JoaoPedroAS51** [comment] 2020-12-18 15:48
Hi guys! Thank you for report. We'll take a look at this issue :)

**Comment by SultonbekovSarvarbek** [comment] 2020-12-19 16:36
The same issue!

**Comment by JoaoPedroAS51** [comment] 2020-12-19 19:21
@oommgg @dz0tto @ximzavivka @steklopod @SultonbekovSarvarbek 

Hey guys! I wasn't able to reproduce the issue using [auth demo code](https://github.com/nuxt-community/auth-module/tree/dev/demo). Can someone try the latest version of v5 and see if persist? Also a repro would be really helpful. You can use this codesandbox template: https://codesandbox.io/s/nuxt-auth-demo-zi53w

Other things that can help is your auth config, the exact version you were using and steps to reproduce the error.

Thank you in advance! :)

**Note: In latest version of v5 the name of laravel providers changed**
- `laravel/jwt` -> `laravelJWT`
- `laravel/sanctum` -> `laravelSanctum`
- `laravel/passport` -> `laravelPassport`

**Comment by greenermoose** [comment] 2020-12-20 01:19
I'm having the same issue, too.

package.json
  "dependencies": {
    "@nuxtjs/auth-next": "5.0.0-1608347545.4014627",
    "@nuxtjs/axios": "^5.12.4",
    "@nuxtjs/dotenv": "latest",
    "core-js": "^3.6.5",
    "nuxt": "^2.14.6"
  },

nuxt.config.js
  /*
   ** Auth module configuration
   ** See https://auth.nuxtjs.org/schemes/local.html#options
   */
  auth: {
    strategies: {
      local: {
        token: {
          property: 'jwt',
          type: 'Bearer'
        },
        user: {
          property: false
        },
        endpoints: {
          login: {
            url: 'auth/local',
            method: 'post'
          },
          user: {
            autoFetch: false,
            property: false,
            url: 'users/me',
            method: 'get'
          },
          logout: false
        }
      }
    }
  },

I'm trying to get nuxt/auth to work with strapi 3.4.0. This is the error I'm hitting:

ExpiredAuthSessionError: Both token and refresh token have expired. Your request was aborted.
    at eval (webpack-internal:///./node_modules/@nuxtjs/auth-next/dist/runtime.mjs:798:17)

**Comment by nathanhenniges** [comment] 2020-12-20 04:10
> @oommgg @dz0tto @ximzavivka @steklopod @SultonbekovSarvarbek
> 
> Hey guys! I wasn't able to reproduce the issue using [auth demo code](https://github.com/nuxt-community/auth-module/tree/dev/demo). Can someone try the latest version of v5 and see if persist? Also a repro would be really helpful. You can use this codesandbox template: https://codesandbox.io/s/nuxt-auth-demo-zi53w
> 
> Other things that can help is your auth config, the exact version you were using and steps to reproduce the error.
> 
> Thank you in advance! :)
> 
> **Note: In latest version of v5 the name of laravel providers changed**
> 
> * `laravel/jwt` -> `laravelJWT`
> * `laravel/sanctum` -> `laravelSanctum`
> * `laravel/passport` -> `laravelPassport`

Currently having the same issue with local auth.  It worked before the latest version and now it always says 

`ExpiredAuthSessionError: Both token and refresh token have expired. Your request was aborted.
    at eval (webpack-internal:///./node_modules/@nuxtjs/auth-next/dist/runtime.mjs:798:17)`

**Comment by JoaoPedroAS51** [comment] 2020-12-20 06:17
@oommgg @dz0tto @ximzavivka @steklopod @SultonbekovSarvarbek @greenermoose @nathanhenniges 

Hey guys! Possible fix in #950. After merged, I would appreciate if someone could test and see if it solves the issue. Thank you in advance! :)

**Closed** 2020-12-20 10:41 UTC
Labels: bug, status: need repro

**Comment by steklopod** [comment] 2020-12-21 07:46
@JoaoPedroAS51 your last commit has broke `USER` request. After successful login it doesn't send `Authorization` header and cookies.

**Comment by ArnoldLC** [comment] 2021-01-11 04:14
```
"nuxt": "^2.14.6",
"@nuxtjs/auth-next": "5.0.0-1608138130.8c7f4dc",
```

I have the same issue:

`ExpiredAuthSessionError: Both token and refresh token have expired. Your request was aborted
`
It happend when I use other endpoint. For example when use my register endpoint with `$axios`. 

The nuxt config is the same of the documentation.

```
auth: {
    strategies: {
      local: {
        token: {
          property: 'access_token',
          type: 'Bearer',
          required: true
        },
        user: {
          property: 'data'
        },
        endpoints: {
          login: {
            url: '/login', method: 'post',
          },
          user: {
            url: '/me', method: 'post',
          },
          logout: {
            url: '/logout', method: 'post'
          }
        }
      }
    },
    redirect: {
      login: '/login',
      logout: '/',
      callback: '/login',
      home: '/'
    }
  },
```

For example I use this register endpoint and this function don't run. Only show the error.

```
this.$axios
        .$post('register', { ... })
        .then()
        .catch()
```

**Comment by arnaud16571542** [comment] 2021-05-25 06:12
I m' able to reproduce this problem, by opening 2 tabs, and logout in 1 tab (which revoke access & refresh tokens). The other tab throw an ExpiredAuthSessionError when trying to navigate.

**Comment by eliyas5044** [comment] 2021-06-03 00:49
Still same problem in the latest version
```
    "@nuxtjs/auth-next": "5.0.0-1622309801.87126e3",
    "@nuxtjs/axios": "^5.13.4",
    "@nuxtjs/proxy": "^2.1.0",
    "nuxt": "^2.15.6",
```
> Request error: ExpiredAuthSessionError: Both token and refresh token have expired. Your request was aborted.

**Comment by NishargShah** [comment] 2021-06-21 19:33
@pi0 Please check again, this problem is still exists in the latest version.

**Comment by sickfar** [comment] 2021-07-13 18:54
"@nuxtjs/auth-next": "5.0.0-1624817847.21691f1" - problem persists

**Comment by jykoaster** [comment] 2021-07-30 06:41
Can somebody reopen it?

**Comment by qiquanlu** [comment] 2021-07-30 15:58
Still facing this issue

**Comment by goldengecko** [comment] 2021-09-11 04:23
I encountered this problem and it turned out that when I was using jsonwebtoken to generate my token at the back end, for the `expiresIn` arg I was passing a string instead of a number (I got it from process.env). If you do this, it assumes you are specifying the number of milliseconds before expiry rather than the number of seconds.

**Comment by cjnahine** [comment] 2021-10-22 02:09
Still facing this issue

**Comment by jonalxh** [comment] 2021-11-03 17:23
Our problem was that in the Django server we defined the same lifetime for access_token and refresh_token, it is necesary to define a different value to make the refresh token work, here my code for Django:
```
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=60),
    'ROTATE_REFRESH_TOKENS': True,  # IMPORTANT
    'BLACKLIST_AFTER_ROTATION': True,  # IMPORTANT
    'UPDATE_LAST_LOGIN': True,
}
```

Is it important for you to know that when you log in with a social account, you need both tokens (access_token and refresh_token) to make nuxt-auth work.

**Comment by norbekoff** [comment] 2022-02-01 09:17
The same issue!

**Comment by Venegrad** [comment] 2022-03-08 17:12
Same issue!

**Comment by bachloxo** [comment] 2022-04-02 15:21
Same issue! any have idea

**Comment by serenalucasjose** [comment] 2022-05-13 14:22
For those still having this issue, in my specific case the problem was that i had some outdated methods that were handling the access token manually like:

```
this.$axios.setToken(accessToken, 'Bearer') 
```

and now all of that logic should be handled via Auth module like:

```
this.$auth.strategy.token.set(accessToken);
this.$auth.strategy.token.sync();
```

after changing those, the error went away. Hope it helps someone.

**Comment by goodpixels** [comment] 2022-08-05 20:09
> For those still having this issue, in my specific case the problem was that i had some outdated methods that were handling the access token manually like:
> 
> ```
> this.$axios.setToken(accessToken, 'Bearer') 
> ```
> 
> and now all of that logic should be handled via Auth module like:
> 
> ```
> this.$auth.strategy.token.set(accessToken);
> this.$auth.strategy.token.sync();
> ```
> 
> after changing those, the error went away. Hope it helps someone.

This is exactly what's causing the problem, BUT unfortunately your proposed solution is flawed and does not fix the issue.

My app connects to two external APIs and I need to create separate Axios instances for them, each has a different baseURL and a different token.

Following the docs on https://axios.nuxtjs.org/helpers#settoken, here's what I'm doing:

**plugins/axios.js**

```
export default function ({ $axios }, inject) {
    const searchAPI = $axios.create();
  
    searchAPI.setBaseURL("https://search-api-url.com");
    searchAPI.setToken(process.env.NUXT_TOKEN_SEARCH_API, "Bearer"); 
  
    inject("searchAPI", searchAPI);
    
    const productAPI = $axios.create();
  
    productAPI.setBaseURL("https://product-api-url.com");
    productAPI.setToken(process.env.NUXT_TOKEN_PRODUCT_API, "Bearer"); 
  
    inject("productAPI", productAPI);
  }
```

But doing so results in the same error as you've encountered:

```
ExpiredAuthSessionError
Both token and refresh token have expired. Your request was aborted.
```

I think the problem is that either the axios module is overwriting the global token OR that the auth module tries to read from the wrong place.

This is still a valid bug, and a pretty annoying at that :(

**Comment by goodpixels** [comment] 2022-08-05 20:10
This really needs to be re-opened.

**Comment by goodpixels** [comment] 2022-08-05 20:17
Setting everything manually via the config object worked for me (but the bug should still be re-opened):

```
export default function ({ $axios }, inject) {
  const searchAPI = $axios.create({
    baseURL: "https://search-api-url.com",
    headers: {
      Authorization: `Bearer ${process.env.NUXT_TOKEN_SEARCH_API}`,
    },
  });

  const productAPI = $axios.create({
    baseURL: "https://product-api-url.com",
    headers: {
      Authorization: `Bearer ${process.env.NUXT_TOKEN_PRODUCT_API}`,
    },
  });

  inject("searchAPI", searchAPI);
  inject("productAPI", productAPI);
}

```

**Comment by invisor** [comment] 2023-02-22 08:41
2.5 years have gone since the bug was reported but is still not fixed. Lol

**Comment by AndreyBan** [comment] 2023-04-04 11:03
Мне помогло только добавление сброса заголовка перед запросом
  ```
this.$axios.setToken(false)
  const r = await this.$axios.$post('/api/forgot-password/', body)
```
В плагинах добавил 

```
export default function ({ app: { $auth, $config }, $axios }) {
  $axios.onRequest((config) => {
    if ($auth.strategy.token.get() && config.headers.authorization !== $auth.strategy.token.get()) {
      $auth.strategy.token.sync()
    } else {
      $axios.setToken($config.token, 'Basic')   // В момент запроса устанавливаем нужный токен в заголовок Authorization
    }
    return config
  })
}
```
