### ISSUE TITLE
How to call my logout api with this.$auth.logout() when using laravelPassport strategy ?

### ISSUE THREAD

**Issue by gilles6** [nuxt-community/auth-module#757] opened 2020-07-09 12:56 UTC
How to call my logout api with `this.$auth.logout()` when using `laravelPassport` strategy in `nuxt.config.js` ?

I'm using `"@nuxtjs/auth-next": "^5.0.0-1593636531.bdce83a"`

**Comment by JoaoPedroAS51** [comment] 2020-12-18 05:52
Duplicate of #712 

---

Docs can be found here: [laravel passport provider](https://auth.nuxtjs.org/providers/laravel-passport) and [oauth2 scheme](https://auth.nuxtjs.org/schemes/oauth2)

**Closed by JoaoPedroAS51** 2020-12-18 05:52 UTC
