### ISSUE TITLE
Cookie headers are not sent in SSR request after new login with nuxt/auth-next  V5.0.0 and axios V5.12.5

### ISSUE THREAD

**Issue by yrestom** [nuxt-community/auth-module#979] opened 2021-01-05 15:17 UTC
I am trying to use cookie method to login with [Frappe framework](https://frappeframework.com/docs/user/en/guides/integration/rest_api/simple_authentication), the login is working fine and i get the 200 status and the cookie, but when auth-next  send a request to user endpoint it not sending the correct header with it and without the cookie and I get 403 status

```other
GET /api/method/frappe.auth.get_logged_user HTTP/1.1
Host: my-site.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:84.0) Gecko/20100101 Firefox/84.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Origin: http://localhost:3000
Connection: keep-alive
Referer: http://localhost:3000/login
```

My nuxt.config.js

```javascript
auth: {
	strategies: {
	  local: {
		token: {
		  required: false,
		  type: false
		},
		endpoints: {
		  login: { url: '/method/login', method: 'post' },
		  logout: { url: '/method/logout', method: 'get' },
		  user: { url: '/method/frappe.auth.get_logged_user', method: 'get' }
		}
	  },
	}
  },
```

I have those versions :

```json
"dependencies": {
	"@nuxtjs/auth-next": "^5.0.0-1608568767.2fe2217",
	"@nuxtjs/axios": "^5.12.5",
	"core-js": "^3.6.5",
	"nuxt": "^2.14.6"
  },
  "devDependencies": {
	"@nuxtjs/vuetify": "^1.11.2"
  }
```

**Comment by acebelowzero** [comment] 2021-02-09 20:22
@yrestom 
Had the same issue but a work around is changing your axios settings in the nuxt.config.js to 

```
axios: {
  credentials: true
}
```
although for security reasons its not recommended

**Comment by bmulholland** [comment] 2022-01-21 09:06
Closing as dupe of https://github.com/nuxt-community/auth-module/issues/1259

**Closed by bmulholland** 2022-01-21 09:06 UTC
Labels: bug
