### ISSUE TITLE
window.crypto and TextEncoder cannot be transpiled to support IE11

### ISSUE THREAD

**Issue by datnm2** [nuxt-community/auth-module#1276] opened 2021-08-28 06:51 UTC
### Version
module: 5.0.0-1611497386.733eabb
nuxt: 2.14.12

### Nuxt configuration
 - [ ] spa

### Nuxt configuration
```
  auth: {
  plugins: ['~/plugins/auth.js'],
  redirect: {
    login: '/login',
    callback: '/auth',
  },
  strategies: {
    aad: {
      scheme: 'oauth2',
      endpoints: {
        authorization: process.env.API_ENDPOINT + '/auth/authorize',
        token: process.env.API_ENDPOINT + '/auth/token',
        userInfo: '',
      },
      token: {
        property: 'access_token',
        type: 'Bearer',
      },
      refreshToken: {
        property: 'refresh_token',
        maxAge: parseInt(process.env.REFRESH_TOKEN_MAX_AGE),
      },
      responseType: 'code',
      grantType: 'authorization_code',
      codeChallengeMethod: 'S256',
      autoLogout: true,
    },
  }
```

> ## Additional information
The problems on IE also:
- msCrypto.subtle.digest() is synchronous
- TextEncoder

#### What is expected?
Feature works on the IE11. Thank you
#### What is actually happening?
The OAuth2 Schema Cannot work on IE11. Through the error:
`"TypeError: Unable to get property 'getRandomValues' of undefined or null reference
   at generateRandomString (eval code:2665:7)
   at _callee8$ (eval code:2330:17)
   at tryCatch (eval code:63:7)
   at invoke (eval code:293:9)
   at Anonymous function (eval code:118:9)
   at asyncGeneratorStep (eval code:5:5)
   at _next (eval code:27:9)
   at Anonymous function (eval code:34:7)
   at Promise (eval code:235:7)
   at Anonymous function (eval code:23:5)"`

**Comment by bmulholland** [comment] 2022-01-21 09:37
Dupe of https://github.com/nuxt-community/auth-module/issues/1084

**Closed by bmulholland** 2022-01-21 09:37 UTC
Labels: bug
