### ISSUE TITLE
My auth state goes to null on page refresh! What could be the issue?

### ISSUE THREAD

**Issue by yiyasha15** [nuxt-community/auth-module#891] opened 2020-11-26 08:04 UTC

**Comment by dvlden** [comment] 2020-11-30 19:12
same here... using laravel-sanctum provider.

**Comment by HenriqueLimaUpp** [comment] 2020-12-01 15:09
same here

**Comment by JosueCarrillo** [comment] 2020-12-02 15:36
same here

**Comment by TobiasJ** [comment] 2020-12-04 12:49
Seems to be all related to https://github.com/nuxt-community/auth-module/issues/809#issuecomment-687750325

Downgrade your `@nuxt/axios` version to the recommended and it should be working as intended. Long story short, auth module is not able to set the correct auth headers when requesting the user endpoint on server-side rendering, thus getting a 401 and no user data.

**Comment by bmulholland** [comment] 2020-12-04 13:39
It would be super helpful if one of you could either trace the bug to its source, or post a working codesandbox repro.

**Comment by msonowal** [comment] 2020-12-14 19:31
@yiyasha15 
This should be fixed in latest versions
https://github.com/nuxt-community/axios-module/pull/452
also update your auth module to latest

and please close this

**Comment by JoaoPedroAS51** [comment] 2020-12-16 16:57
Closing here since latest version of `auth-next` should solve this issue. [`@nuxtjs/axios` updated to `v5.12.4`](https://github.com/nuxt-community/axios-module/releases/tag/v5.12.4). Feel free to reopen if issue persists.

**Closed by JoaoPedroAS51** 2020-12-16 16:57 UTC
