### ISSUE TITLE
watchState not called on change

### ISSUE THREAD

**Issue by iranagame** [nuxt-community/auth-module#1149] opened 2021-04-27 20:50 UTC
Is there anyway to watch token changes via `watchState` (when new token fetched via refresh token) or any other similar methods? I tried the following way but did not get any success!

```
      this.$auth.$storage.watchState('token', v => {
        console.log('token', v);
      });
```

**Comment by Rednas83** [comment] 2021-09-28 09:49
I have the same question.

It doesn't seems to behave according the docs
```
      this.$auth.$storage.watchState("test", (value) => {
        console.log("watched", value) // Issue: Callback never called when "test" changes
      })
      this.$auth.$storage.setState("test", this.$auth.$state.test ? this.$auth.$state.test++ : 0) // Issue: Not triggering callback function and only updates value after reload
      console.log("testA:", this.$auth.$state.test) // returns undefined (expected 1)
      // this.$auth.$storage.$state.test++ // Returns TypeError: Cannot set properties of undefined (setting 'test')
      console.log("testB:", "error" || this.$auth.$state.test) // returns error (expected 2)
      this.$auth.$state.test++ // Issue: Not triggering callback function and only updates value after reload
      console.log("testC:", this.$auth.$state.test) // returns undefined (expected 3)
```
**Actual behaviour**
Variable is updated and callback is not called
Variable is only updated on the screen after reload. 

**Expected behaviour**
Callback is called when variable is changed
Variable on screen is updated without the need of a reload. Why is this?

**Comment by bmulholland** [comment] 2022-01-21 10:03
Dupe of https://github.com/nuxt-community/auth-module/issues/156

**Closed by bmulholland** 2022-01-21 10:03 UTC
Labels: question
