### ISSUE TITLE
@nuxtjs/auth-next conflicts with vuex-module-decorators

### ISSUE THREAD

**Issue by GKennyKwok** [nuxt-community/auth-module#990] opened 2021-01-11 15:29 UTC
### Version
"nuxt": "^2.14.6",
"@nuxt/typescript-runtime": "^2.0.0",
"@nuxt/typescript-build": "^2.0.3",
"vuex-module-decorators": "^1.0.1"
"@nuxtjs/auth-next": "^5.0.0-1608568767.2fe2217",

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 -   modules: [
    '@nuxtjs/axios',
    '@nuxtjs/auth-next',
    'bootstrap-vue/nuxt',
  ],

#### Use Class to define VuexModule under TypeScript, which will be overwritten by auth-next, resulting in invalid @action
Don't use'@nuxtjs/auth-next', it's normal

https://codesandbox.io/s/optimistic-shadow-68pc9

**Comment by GKennyKwok** [comment] 2021-01-13 08:29
Same as @nuxtjs/auth

**Comment by bmulholland** [comment] 2021-01-14 17:00
Sorry, I don't understand. What's the issue? When does it happen? What conflicts? What result does the conflict has?

**Comment by GKennyKwok** [comment] 2021-01-15 15:32
@Action in client/store/account.ts Will fail because of using auth，If you don't use auth, you can use dispatch to stimulate

**Comment by bmulholland** [comment] 2021-01-15 16:44
Sorry but that still doesn't help, and your codesandbox won't load for me - says there's an error fetching sandbox. `client/store/account.ts` is not a file in this repository, and I don't know what you're talking about with dispatch.

What would be most helpful is if you traced down the issue to what part of this library is causing the problem, and why.

I'm going to close this ticket because I don't have enough information to understand the problem or reproduce it. I'll be happy to re-open it later, if I get enough information to take action.

**Closed by bmulholland** 2021-01-15 16:44 UTC
Labels: bug

**Comment by GKennyKwok** [comment] 2021-01-15 16:49
I made my project public.

https://github.com/GKennyKwok/vue-mooli

**Comment by tzaborski** [comment] 2021-04-23 11:12
+1 same issue
