### ISSUE TITLE
Not redirecting after login when going directly on the route

### ISSUE THREAD

**Issue by mathieutu** [nuxt-community/auth-module#134] opened 2018-04-11 09:20 UTC
### Version

[v4.1.0](https://github.com/nuxt-community/auth-module/releases/tag/v4.1.0)

### Reproduction link

[https://nuxt-auth.herokuapp.com/secure](https://nuxt-auth.herokuapp.com/secure)

### Steps to reproduce

Hi,
When accessing directly on a secured page, the redirect key is not set in the state, and there is not redirection after login.
This is visible in the demo: access directly this page without be logged, and you will not have the `$auth.$state.redirect` message: https://nuxt-auth.herokuapp.com/secure

### What is expected ?

![Screen Shot 2018-04-11 at 11.19.27.png](https://cmty.s3.eu-west-1.amazonaws.com/102371998/7e64b630-3d69-11e8-b907-4158a744457b.png)

And redirection after login

### What is actually happening?

![Screen Shot 2018-04-11 at 11.19.36.png](https://cmty.s3.eu-west-1.amazonaws.com/102371998/8132f160-3d69-11e8-9c4e-a7b51bcd1a53.png)

And no redirection after login.

### Additional comments?

Thanks!

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c100">#c100</a>)</em></sub></div>

**Comment by stevepop** [comment] 2018-05-03 14:07
Hi,

I am having the same issue myself on a project I am currently working on. When an un-authenticated user visits `/member/profile`, the user is redirected to the login page. After logging in, they are not redirected to the intended page but to the normal link redirect from login. 

I see that this issue was raised since 22 days ago and not responded to. Is there a work-around I can implement before this issue is resolved?

Thanks!

**Comment by Lahori-Jawan** [comment] 2018-05-14 05:29
I raised this issue on [nuxt community](https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c133) but no one responded. @pi0 would you shed some light on this issue?

**Comment by mathieutu** [comment] 2018-05-14 07:59
@SnooHD and @belak had some solutions: 
- https://github.com/nuxt-community/auth-module/issues/165#issuecomment-388597785
- https://github.com/nuxt-community/auth-module/issues/165#issuecomment-388673580

Guys, may you submit a PR to fix that?

Thanks!

**Comment by Lahori-Jawan** [comment] 2018-05-14 12:25
After failing to find any easy/reliable solution I came up with this one:
`login.vue`
```
methods: {
      login () {
	localStorage.setItem('redirect', this.$route.path)
	this.$auth.loginWith('google')
      }
}
```
and then in callback/redirect route
`callback.vue`

```
export default {
	mounted () {
		this.$router.push(localStorage.getItem('redirect'))
	}
}
```
Although everything works just fine but after redirecting to **desired** link it is redirected back to home page which i don't understand why.

**Comment by stevepop** [comment] 2018-05-14 12:39
@Lahori-Jawan,The problem with relying on LocalStorage is that it is client side which can change at any point in time. 
I am not so sure this is the best way to deal with this but if it works for you, it may be a temporary work-around

**Comment by Lahori-Jawan** [comment] 2018-05-14 12:44
yeah, for now I am just looking for a work around but the problem is that after redirecting to the page it redirects back to homepage, can you guess Why @stevepop ?

**Comment by SnooHD** [comment] 2018-05-14 12:45
@Lahori-Jawan I think this happens because the `loggedIn` watcher is still triggered, redirecting you to the login redirect option.

It is surely possible to prevent this through a custom middleware where you set `store.auth.redirect`
Because the watcher redirects you this value if its set.

But i think the solution i gave using a [cookie](https://github.com/nuxt-community/auth-module/issues/165#issuecomment-388597785) or the solution @belak gave with the [query](https://github.com/nuxt-community/auth-module/issues/165#issuecomment-388673580) would be better.

**Comment by Lahori-Jawan** [comment] 2018-05-14 12:52
@SnooHD  Thank you for the input. Actually I am avoiding those solutions for now bec. they both seem pretty daunting for this simple scenario. Could you give me a bit more insight to your suggestion? do you mean like `store.auth.redirect = false` ?

**Comment by SnooHD** [comment] 2018-05-14 12:55
@Lahori-Jawan `store.auth.redirect = '/path-you-want-to-redirect-to'` so in your case `localStorage.getItem('redirect')`

**Comment by nitescent** [comment] 2018-06-11 12:11
Is someone working on a fix for this bug?

**Comment by SnooHD** [comment] 2018-06-11 13:42
@nitescent If you truly want to solve it, there are 2 ways to do it until a better solution is integrated.
Both can be found here: #165

**Comment by zolotyx** [comment] 2018-07-27 07:16
Please, take a look at my workaround

Create plugins/auth.js file
Add plugins: ['~/plugins/auth.js'], to auth section of the nuxt.config.js
here is a content of the auth.js file: https://gist.github.com/zolotyx/b4e7fda234b3572fb7adaf11391f8eef

**Comment by nitescent** [comment] 2018-07-27 15:38
@zolotyx your solution seems to work but I notice in case there were query params present in the URL they are lost.

**Comment by nitescent** [comment] 2018-07-28 15:36
Thanks @zolotyx, I'm using your solution now

**Comment by wangtheo** [comment] 2018-07-29 15:33
Here's a fix that worked for me:

Go to .nuxt/auth/auth.js and change

`redirect (name, noRouter = false) {
    if (!this.options.redirect) {
      return
    }`

to

`redirect (name, noRouter = false) {
    if (!$auth.redirect) {
      return
    }`

**Comment by redijedi** [comment] 2018-07-30 12:32
@zolotyx The workaround continually results in `Cannot read property 'options' of undefined`. I've added it to the plugins section of auth. Is there something I'm missing?

**Comment by joshink** [comment] 2018-08-09 22:32
@redijedi not sure if you figured it out by now, but you need to add the plugin to the ``auth`` setting, __*not*__ the global plugins:

```
auth: {
  ...
  plugins: ['~/plugins/auth.js']
}
```

**Comment by redijedi** [comment] 2018-08-10 11:52
@joshink Thanks, but that still doesn't work. It is only in the auth block but I get
```
[1] Caught error: TypeError TypeError: Cannot read property 'options' of undefined
[1]     at Auth.redirect (src/plugins/auth.js:8:0)
[1]     at module.exports.__WEBPACK_IMPORTED_MODULE_0__middleware__.a.auth (.nuxt/auth/middleware.js:31:0)
[1]     at promisify (.nuxt/utils.js:203:0)
[1]     at middlewareSeries (.nuxt/utils.js:184:0)
[1]     at module.exports.__webpack_exports__.default (.nuxt/server.js:114:0)
[1]     at <anonymous>
[1]     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by redijedi** [comment] 2018-08-10 12:32
@joshink Actually, it was my fault. I was rewriting the `redirect` function as an arrow function to make eslint happy. Not doing that got rid of the error, but the app still doesn't redirect to the path in the query string. Could be my fault...digging.

**Comment by joshink** [comment] 2018-08-10 15:36
@redijedi Yeah, I think all that code actually does is pass the redirect to the login page for you. It was not redirecting automatically for me either. You should be able to do something like this in your login page's methods.

```javascript
async handleLogin () {
  await this.$auth.login( { data } )
  this.$router.go(decodeURIComponent(this.$route.query.redirect || "/"))
}
```
Hope that helps!

**Comment by shawnlauzon** [comment] 2018-11-08 18:42
The workaround provided by @zolotyx resolves the problem for me. As @SnooHD says, the problem is that when Vuex is used, the redirect is stored in Vuex but after the redirect, the store is lost and so it forgot where to redirect to.

The workarounds referenced in #165 may be "better" (I don't really know), but they seem to be more effort than the above workaround, and so I prefer the simpler workaround until something is integrated into the system itself.

**Comment by SnooHD** [comment] 2018-11-08 19:18
@shawnlauzon
My solution uses cookies, @belak uses a query and @zolotyx using the localStorage.
I would say it hardly matters, it is not better or worse.

**Comment by hashinteractive** [comment] 2019-01-18 15:42
Does anyone know if any of these options work with an Identity Provider/auth0 protocol?

@SnooHD or @zolotyx do either of you know if your solutions would work with an identity provider in which the user is redirected off the nuxt site to the identity provider for verification and brought back to the callback url? I have tried both solutions to no avail as the redirects are not working (even though they are stored as cookies in @SnooHD solution).

Any ideas on this would be greatly appreciated!

**Comment by andershagbard** [comment] 2019-02-11 15:26
I've ran into this issue as well. My mistake was having `auth: false` set on my login page. If you have it, just remove it.

´´´javascript
<script>
  export default {
    auth: false
  }
</script>
´´´

**Comment by Harry72** [comment] 2019-02-15 08:27
> I've ran into this issue as well. My mistake was having `auth: false` set on my login page. If you have it, just remove it.
> 
> ```js
> <script>
>   export default {
>     auth: false
>   }
> </script>
> ```

Thank you. This fixed my issue with the Auth Module.

**Comment by amdp** [comment] 2019-03-27 19:47
In my case the "error" was related to this:

https://github.com/nuxt-community/auth-module/issues/58

setting the user propertyName to flase made the trick:

`user: { url: '/api/auth/me/', propertyName: false },`

**Comment by MathiasCiarlo** [comment] 2019-04-14 10:30
Hi all, I have just added a [PR](https://github.com/nuxt-community/auth-module/pull/333) which fixes the root cause of this issue. The issue is that the storage component did not support setting cookies server side. The PR lets the storage add a Set-cookie header to the response, so that the intended protected path is available after login.

**Comment by yurriiy** [comment] 2019-05-15 10:12
hi all, there is information about when it will be released?

**Comment by MathiasCiarlo** [comment] 2019-05-15 11:39
@yurriiy It depends on the maintainers. We are awaiting feedback from them. We need to scream together to get some attention I think :)

**Comment by stevepop** [comment] 2019-05-15 11:43
@MathiasCiarlo Thanks for the PR. I am definitely waiting for this to be merged soon!

**Comment by Kinvaras** [comment] 2019-05-15 11:51
@MathiasCiarlo Thanks for the PR. Hope this PR to be considered by our dearly maintainers :D

**Comment by albanafmeti** [comment] 2019-05-16 12:46
> I've ran into this issue as well. My mistake was having `auth: false` set on my login page. If you have it, just remove it.
> 
> ```js
> <script>
> export default {
>   auth: false
> }
> </script>
> ```

This is not working properly. It fixes the problem temporary.
Somebody should merge that PR. This is a critical issue.

Thanks for the PR. Hope that's the solution.

**Comment by geeky-geek** [comment] 2019-05-24 22:14
It affects us too :/
@MathiasCiarlo thanks for the PR!

**Comment by pi0** [comment] 2019-05-30 21:05
Should be fixed in [v4.6.0](https://github.com/nuxt-community/auth-module/releases/tag/v4.6.0). Sorry for this late update.

**Closed by pi0** 2019-05-30 21:05 UTC
Labels: bug, cmty:bug-report

**Comment by olivermaldonado** [comment] 2019-06-20 00:30
Is it just me, or is anybody else still having this exact issue? Even after v4.6.0..

**Comment by guesskingf** [comment] 2019-06-25 03:27
Still got this issue, can't set redirect in auth store after v4.6.0 @pi0

**Comment by lpeppe** [comment] 2019-07-01 14:51
Yes, same here...

**Comment by 8bu** [comment] 2019-07-03 00:02
got the same issue here, tried many work arounds I found on this issue feedback but none of them worked.

**Comment by pi0** [comment] 2019-07-03 09:01
I wonder if newly reported issues are exactly the same. Please create new issue with reproduction code (or at least URL) + steps

**Comment by 8bu** [comment] 2019-07-04 17:25
I just found out that redirect issue will be solved when disable vuex-persist plugin that I added before.

**Comment by 8bu** [comment] 2019-07-11 02:03
Btw, the plugin will be conflict a little bit with some vuex persist plugin. Please update the doc to tell people do not include `auth` module when they use vuex-persist plugin or localStorage to store vuex state.

**Comment by AllanPinheiroDeLima** [comment] 2019-07-18 13:16
I've answered in another issue, but I'll put here too:

The thing is that is seems that the nuxt auth plugin waits this property to be defined to redirect to login. There is no need to make workarounds, but a PR may be welcome. 

Here is my code: 

```
auth: {
strategies: {
      local: {
        endpoints: {
          login: { url: '/auth/login', method: 'post', propertyName: 'token' },
          user: { url: '/auth/user', method: 'get', propertyName: false },
          logout: { url: '/auth/logout', method: 'post' }
        },
        // tokenRequired: true,
        // tokenType: 'Bearer'
      }
    },
    redirect: {
      login: '/public/login',
      home: '/',
      logout: '/public/login'
    }
  }
```

**Comment by raquelfleeet** [comment] 2020-06-15 07:33
## RETURNING TO THE REQUEST PAGE AFTER LOGIN

#### Build in a system for keeping track of what page was originally requested and redirect to it after a successful login can be done in 2 steps. 

As @belak said:
> The query param solution is better, 

However, for me his solution didn’t work as I have problems when trying to import the helpers from the library. Nevertheless, there is a most **simple solution**:


- Create an auth-guard middleware that saves the requested url and redirects to the login with such url saved in the query params.
  - Declare the middleware in the nuxt config and disable @nuxtjs/auth redirect option as it will be done in the new middleware. 

	nuxt.config.js:
	```javascript
  	router: {
    		middleware: ['auth-guard'],
  	},
  	auth: {
    	vuex: { namespace: '_auth' },
    	redirect: false,
    	localStorage: false,
    	},
    strategies: {
      local: {
        endpoints: {
          login: {
            url: '/auth/login',
            method: 'post',
            propertyName: 'access_token',
          },
          logout: {
            url: '/auth/logout',
            method: 'post',
          },
          user: {
            url: '/auth/me',
            method: 'get',
            propertyName: false,
          },
        },
      },
    }
	```
  - When the route path is different than login save such path and redirect to it if the user is NOT logged in. 

	middleware/auth-guard.js

	```javascript
	export default async function({ $auth, route, redirect }) {
  	if (route.path !== '/login') {
    	let REDIRECT_URL = '/login?redirect=' + route.path
    	if (!$auth.loggedIn) {
      		redirect(REDIRECT_URL)
    	}
 	 }
	}
	```

- Use the query params for redirect after a successful login to the saved path if exists.

pages/login.vue

```javascript
  const handleSubmit = async () => {
      try {
        errorMsg.value = undefined
        await form.submit()
        let redirect_url = root.$route.query.redirect || '/dashboard'
        root.$router.push({
          path: redirect_url,
        })
      } catch (error) {
        errorMsg.value = t(`auth.login.error.${error.code}`)
      }
    }
```

**Comment by raquelriobo** [comment] 2020-06-15 07:36
## RETURNING TO THE REQUEST PAGE AFTER LOGIN

#### Build in a system for keeping track of what page was originally requested and redirect to it after a successful login can be done in 2 steps. 

As @belak said:
> The query param solution is better, 

However, for me his solution didn’t work as I have problems when trying to import the helpers from the library. Nevertheless, there is a most **simple solution**:


- Create an auth-guard middleware that saves the requested url and redirects to the login with such url saved in the query params.
  - Declare the middleware in the nuxt config and disable @nuxtjs/auth redirect option as it will be done in the new middleware. 

	nuxt.config.js:
	```javascript
  	router: {
    		middleware: ['auth-guard'],
  	},
  	auth: {
    	vuex: { namespace: '_auth' },
    	redirect: false,
    	localStorage: false,
    	},
    strategies: {
      local: {
        endpoints: {
          login: {
            url: '/auth/login',
            method: 'post',
            propertyName: 'access_token',
          },
          logout: {
            url: '/auth/logout',
            method: 'post',
          },
          user: {
            url: '/auth/me',
            method: 'get',
            propertyName: false,
          },
        },
      },
    }
	```
  - When the route path is different than login save such path and redirect to it if the user is NOT logged in. 

	middleware/auth-guard.js

	```javascript
	export default async function({ $auth, route, redirect }) {
  	if (route.path !== '/login') {
    	let REDIRECT_URL = '/login?redirect=' + route.path
    	if (!$auth.loggedIn) {
      		redirect(REDIRECT_URL)
    	}
 	 }
	}
	```

- Use the query params for redirect after a successful login to the saved path if exists.

pages/login.vue

```javascript
  const handleSubmit = async () => {
      try {
        errorMsg.value = undefined
        await form.submit()
        let redirect_url = root.$route.query.redirect || '/dashboard'
        root.$router.push({
          path: redirect_url,
        })
      } catch (error) {
        errorMsg.value = t(`auth.login.error.${error.code}`)
      }
    }
```

**Comment by caroait** [comment] 2020-07-09 06:02
I was fighting with this error too and I solve it adding this line before redirect to the login

`$auth.$storage.setUniversal('redirect', path)`

**Comment by renztoygwapo** [comment] 2020-07-19 01:55
Hi @caroait can you show me your code where did you put that ?

Thanks

**Comment by caroait** [comment] 2020-07-19 23:04
Hi @renztoygwapo I use it before do `$auth.login()`

**Comment by Dpezz** [comment] 2020-08-04 04:06
i resolve this add in vuex-persist.js plugin:

`new VuexPersistence({
      ...
      strictMode: true,
     ...
    }).plugin(store);`

**Comment by Oscar2av** [comment] 2020-09-02 13:27
I had a similar problem. I had to **redirect the user depending on the Role** (User or admin), so, the solution of just writing one common redirection did not work for me. I did the following, I have created a vue page called redirect.vue and there I wrote a middleware that checks the role of the user in order to redirect to the correct page (getting the users info from the vuex store), this solution may not be the best one but works. I hope this help someone!

**redirect.vue (page):**

```
<template>
  <div></div>
</template>

<script>
export default {
  middleware: 'redirect_middleware',
  data() {
    return {}
  }
}
</script>
```

**redirect_middleware.js (middleware)**

```
export default function({ store, redirect }) {
  if (
    store.state.auth.loggedIn &&
    (store.state.auth.user.role === 'user'
  ) {
    return redirect('/userspage')
  } else if (
    store.state.auth.loggedIn &&
    store.state.auth.user.role === 'admin'
  ) {
    return redirect('/adminpage')
  }
}

```
**Note**: For this to work, make sure that in the users table is a field called "role"

**auth object inside nuxt.config.js** 
  ```
auth: {
    strategies: {
      local: {
        endpoints: {
          login: {
            url: 'api/auth/login',
            method: 'post',
            propertyName: 'token'
          },
          logout: {
            url: 'api/auth/logout',
            method: 'get'
          },
          user: {
            url: 'api/me',
            method: 'get',
            propertyName: 'data'
          }
        }
      }
    },
    redirect: {
      home: '/auth/redirect',
      login: '/auth/login',
      logout: '/'
    },
    fullPathRedirect: true
  }
```

From Colombia to the world! :)

**Comment by yondifon** [comment] 2021-03-14 17:41
> ## RETURNING TO THE REQUEST PAGE AFTER LOGIN
> #### Build in a system for keeping track of what page was originally requested and redirect to it after a successful login can be done in 2 steps.
> As @belak said:
> 
> > The query param solution is better,
> 
> However, for me his solution didn’t work as I have problems when trying to import the helpers from the library. Nevertheless, there is a most **simple solution**:
> 
> * Create an auth-guard middleware that saves the requested url and redirects to the login with such url saved in the query params.
>   
>   * Declare the middleware in the nuxt config and disable @nuxtjs/auth redirect option as it will be done in the new middleware.
>     nuxt.config.js:
>     ```js
>     router: {
>     		middleware: ['auth-guard'],
>     },
>     auth: {
>         vuex: { namespace: '_auth' },
>         redirect: {
>              login: false,
>              logout: '/login',
>              callback: false,
>              home: false,
>          },
>          localStorage: false,
>     },
>     strategies: {
>       local: {
>         endpoints: {
>           login: {
>             url: '/auth/login',
>             method: 'post',
>             propertyName: 'access_token',
>           },
>           logout: {
>             url: '/auth/logout',
>             method: 'post',
>           },
>           user: {
>             url: '/auth/me',
>             method: 'get',
>             propertyName: false,
>           },
>         },
>       },
>     }
>     ```
>   * When the route path is different than login save such path and redirect to it if the user is NOT logged in.
>     middleware/auth-guard.js
>     ```js
>     export default function({ $auth, route, redirect }) {
>     if (route.path !== '/login') {
>     	const REDIRECT_URL = '/login?redirect=' + route.path
>     	if (!$auth.loggedIn) {
>       		redirect(REDIRECT_URL)
>     	}
>      }
>     }
>     ```
> * Use the query params for redirect after a successful login to the saved path if exists.
> 
> pages/login.vue
> 
> ```js
>   const handleSubmit = async () => {
>       try {
>         errorMsg.value = undefined
>         await form.submit()
>         let redirect_url = root.$route.query.redirect || '/dashboard'
>         root.$router.push({
>           path: redirect_url,
>         })
>       } catch (error) {
>         errorMsg.value = t(`auth.login.error.${error.code}`)
>       }
>     }
> ```

To make it dynamic. You can update the links to look like this.

```ts
export default function ({ $auth, route, redirect }: any) {
    if (route.path !== $auth.options.redirect.login) {
        if (!$auth.loggedIn) {
            redirect($auth.options.redirect.login, { redirect: route.path })
        }
    }
}
```

**Comment by OndraRehounek** [comment] 2021-05-16 06:40
I tried to follow the idea of @raquelriobo but it seemed to me little bit "too manual". But it gave me idea of this workaround since (maybe only in my case) there is the redirect path kept in localStorage (but redirect is not happening (just sometimes...).

I disabled home redirect in nuxt.config.js auth settings:

```
  auth: {
    redirect: {
      login: '/auth/login/',
      logout: '/auth/logout/',
      callback: false,
      home: false
    },
   ....
```

And then, when user tries to login I do redirect manually:

```
  // pages/auth/login.vue
  methods: {
    async login() {
      try {
        await this.$auth.loginWith('local', { data: { userName: this.userName, password: this.password } })
      } catch (e) {
        this.$toast.error(e.message)
      }

     this.$router.push(localStorage['auth.redirect'] ? { path: localStorage['auth.redirect'] } : { name: 'index' })
   }
   ....
```

So only manual `localStorage['auth.redirect']` seems to be needed to solve (my) redirect issue but I am not sure if it will work for everyone since it is happening quite randomly in our app and might be just some async problem.

**Comment by KunalAggarwal** [comment] 2021-05-29 22:13
Refer to https://github.com/nuxt-community/auth-module/issues/205#issuecomment-850906221 in case login logout redirection doesn't work for someone. I managed to get it working as mentioned in that comment. Might be helpful for someone.

**Comment by Didza** [comment] 2021-07-26 23:33
This nuxt auth module will make be my final push to using react. It just has so much inconsistences.

**Comment by kon3ko** [comment] 2022-02-13 17:07
> i resolve this add **[strictMode: true]** in vuex-persist.js plugin:
> 
> `new VuexPersistence({ ... strictMode: true, ... }).plugin(store);`

Thank a lot man!!
