### ISSUE TITLE
Auth Redirect to login when first page load

### ISSUE THREAD

**Issue by KareemDa** [nuxt-community/auth-module#1332] opened 2021-10-27 17:19 UTC
### Version
module: 2.15.7
nuxt: 5.0.0-1624817847.21691f1

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt configuration
<details>

```
"auth":{
  "strategies":{
    "local":{
      "user":{
        "property":false
      },
      "token":{
        "maxAge":2592000 //  set to 1 month
      },
      "endpoints":{
        "login":{
          "url":"/login",
          "method":"post",
          "propertyName":"token"
        },
        "user":{
          "url":"/me",
          "method":"get",
          "property":false
        }
      }
    }
  },
  "redirect":{
    "login":"/auth/login"
  }
},
```

</details>

#### Steps to reproduce
- start project
- open browser and login
- close the browser
- reopen the  browser and open the project

### What is expected?
should be working without redirection into login page

### What is actually happening?
Redirect into login page

## Additional information
I'm using `dispatcher` inside  `nuxtServerInit` to get data from API which need Authorization.
when opening the browser for the first time, First request always sent without `Authorization` in header: 

I've tried to console `this.$axios.defaults.headers` in order to debug this issue : 

first request header when browser is loaded:
![image](https://user-images.githubusercontent.com/42810389/139114641-d4d1d43e-4bd5-449a-a420-3b83bd365886.png)

after refreshing page:
![image](https://user-images.githubusercontent.com/42810389/139114485-4c892a3f-ed1e-4b6f-8987-0a982eaf4087.png)

**Comment by mohsenMJ** [comment] 2021-11-01 09:20
I have exactly the same error , when opening browser and enter a secure url to my website , even if the user is logged in , it redirects me to /login page , if I refresh the page again , it will goes the my http://mydomain.com/ page

p

**Comment by men232** [comment] 2021-11-17 11:40
I just noted one weird thing, `$auth.loggedIn` always `false` after  `loginWith` calling. Try to initialize vuex with default auth state, like this:
```
// store/state.js

export default () => ({
  pageLoader: false,
  auth: {
    loggedIn: false,
  },
});

```

**Comment by men232** [comment] 2021-11-22 13:12
Not really, had to disable redirect to home (set home = false in config)
and call router.push after success loginWith

**Comment by KareemDa** [comment] 2021-11-27 09:23
> had to disable redirect to home (set home = false in config)

this also didn't work for me

**Comment by MilesWuCode** [comment] 2021-11-30 08:04
SSR : same problem

**Comment by MilesWuCode** [comment] 2021-12-01 02:53
@KareemDa 
i try change env name  , API_URL to APIURL (or other name) is work for me

**Comment by KareemDa** [comment] 2021-12-01 08:04
> i try change env name , API_URL to APIURL (or other name) is work for me
> 
> *

but I don't have env file in my project

**Comment by claytongf** [comment] 2021-12-07 19:44
In my case, when I refresh the page or when I have a link with target="_blank", the app redirects to the login page, even if the loggedIn property is true.

**Comment by alexisohayon** [comment] 2021-12-29 21:11
Hi! Have the same problem, did anyone successfully fixed this issue without the env thing?

**Comment by KareemDa** [comment] 2021-12-29 21:35
Not Yet !!

**Comment by BennaceurHichem** [comment] 2022-01-08 14:14
Same issue here, any updates ?

**Comment by KareemDa** [comment] 2022-01-08 14:16
@JoaoPedroAS51 @pi0 
Kindly have a look at this bug.

**Comment by bmulholland** [comment] 2022-01-19 11:39
We don't have time to set up and debug the exact setup described here; it would literally take me hours just to arrive at a point where I could begin to investigate this issue on my own. Therefore, your own investigation is needed. If you have this reproduced, please track down what, if any, the bug is within the auth module. Specific logic & lines of code with well-reasoned explanations for why they're wrong are most helpful. If you'd like this fixed in a realistic timeframe, I recommend creating a PR. Until we have this, I cannot realistically act on this report.

**Comment by bmulholland** [comment] 2022-01-21 09:16
For SSR issues, see here: https://github.com/nuxt-community/auth-module/issues/1197

**Closed by bmulholland** 2022-01-21 09:16 UTC
Labels: bug

**Comment by KareemDa** [comment] 2022-01-28 20:22
@bmulholland @pi0 
I've figured out that the problem that auth cookies are set to session-only by default: [documentation link](https://auth.nuxtjs.org/api/options/#cookie).

so when opening the browser for the first time, cookies are not set. Thus, `nuxt-auth` can't get the `token` from cookie and user request will return 401, 

adding:
```
cookie: {
	options: {
		expires: 8,
	},
},
```
to `auth` object in `nuxt.config.js` resolves the problem 


But I think the behaviour should be changed by default (I don't have to change auth options in order to make it working as expected)

**Comment by bmulholland** [comment] 2022-01-31 10:52
@KareemDa If you think the defaults should be changed, please create a Discussion with your proposal. You'll need to make a compelling case, including communication and considering adverse effects, since it will impact large numbers of people.

**Comment by Venegrad** [comment] 2023-02-28 22:00
> lves the problem

Not working for me, first redirect is not working.
