### ISSUE TITLE
Setting JWT Refresh Token from login endpoints

### ISSUE THREAD

**Issue by rikoz** [nuxt-community/auth-module#398] opened 2019-06-30 03:13 UTC
### What problem does this feature solve?

Hello, I have a feature request and i need help from anyone who can help

What I have::
please i'm making use of JWT setting the access token in the property name... the problem is access token expires after some minutes and becomes invalid throwing a 401 (Unauthorized) error and this will make the application to logout.

What I want to acheive::
A way to set the refresh token so when access token expires and throws such error, I should intercept to use refresh token to fetch a new access token and then repeat request.

I'm using DRF for backend.
I really need your help as this app deploys in few days and i need to fix it up

Thanks
![Screenshot from 2019-06-30 03-57-19.png](https://cmty.s3.eu-west-1.amazonaws.com/102371998/18c61840-9ae3-11e9-b306-055a90a7ce49.png)

![Screenshot from 2019-06-30 03-56-28.png](https://cmty.s3.eu-west-1.amazonaws.com/102371998/1d723b30-9ae3-11e9-b306-055a90a7ce49.png)

![Screenshot from 2019-06-30 04-01-42.png](https://cmty.s3.eu-west-1.amazonaws.com/102371998/71ea3960-9ae3-11e9-b306-055a90a7ce49.png)

### What does the proposed changes look like?

Please add another optional field to login endpoint that sets refresh token.... I already see the auth module has the function to set it. An axios interceptor will take care of the rest feature of having to fetch a new access token once expired using the refresh token in payload.
Also a new endpoint to specify what url is called using this refresh token to fetch access

![Screenshot from 2019-06-30 04-07-39.png](https://cmty.s3.eu-west-1.amazonaws.com/102371998/45cc2ae0-9ae4-11e9-b306-055a90a7ce49.png)

To look something like this
![Screenshot from 2019-06-30 04-12-15.png](https://cmty.s3.eu-west-1.amazonaws.com/102371998/e98e0310-9ae4-11e9-b306-055a90a7ce49.png)

and then a $auth.tokenRefresh function.

Thanks

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c366">#c366</a>)</em></sub></div>

**Comment by geoffreylzf** [comment] 2019-07-07 11:56
I also waiting this features to be merged, for short term solution, I set the jwt token expire time to 8 hour

**Comment by JoaoPedroAS51** [comment] 2019-07-11 13:16
Hi @rikoz, we are working on refresh support. Check this out #361 

We haven't finished yet, but at the meantime you can use the new [branch (feat/refresh)](https://github.com/nuxt-community/auth-module/tree/feat/refresh).

You can find the docs in the PR.

**Comment by rikoz** [comment] 2019-07-14 13:36
Okay, I will check it out now.

Let me know when it's updated into the main branch so i can update my node package. I will be waiting

Can you give me a direct link to docs

thanks I appreciate.

**Comment by JoaoPedroAS51** [comment] 2019-07-14 14:04
@rikoz I'll let you know when we merge it.

Docs can be found [#361](https://github.com/nuxt-community/auth-module/pull/361)

**Comment by rikoz** [comment] 2019-07-15 02:28
Okay thanks, seen

**Comment by mckraemer** [comment] 2020-02-20 01:17
Any updates?

**Comment by danielmoeck** [comment] 2020-02-23 01:15
> @rikoz I'll let you know when we merge it.
> 
> Docs can be found here [#361](https://github.com/nuxt-community/auth-module/pull/361)

Hey Joao, do you have any news? 
I think this is a feature many people need :)

Is there a way I can help?

**Comment by JoaoPedroAS51** [comment] 2020-02-23 05:35
> Hey Joao, do you have any news?
> I think this is a feature many people need :)
> 
> Is there a way I can help?

Hi @danielmoeck, I'm sorry, I don't have any news about it. I had to stop working a few months ago due to personal problems.

But yeah I agree, many people need this feature! Actually, I use this branch in my project in production! For me it works fine and stable.

I guess is up to @pi0 to make the final reviews and merge it.

**Comment by JoaoPedroAS51** [comment] 2020-02-23 05:39
@danielmoeck @mckraemer 
I just released a new update, the [branch feat/refresh](https://github.com/nuxt-community/auth-module/tree/feat/refresh) is up-to-date now ;)

**Comment by danielmoeck** [comment] 2020-02-23 11:52
> 
> 
> @danielmoeck @mckraemer
> I just released a new update, the [branch feat/refresh](https://github.com/nuxt-community/auth-module/tree/feat/refresh) is up-to-date now ;)

Thank you!

**Comment by danielmoeck** [comment] 2020-02-25 15:59
oh damn @JoaoPedroAS51
When I call the /users/me route the auth-module will send Authorization: JWT undefined. 
It worked with master. Do you have a hint? :)

**Comment by JoaoPedroAS51** [comment] 2020-02-25 18:56
Hey @danielmoeck! Let's find out together!
Can you show me your auth config in `nuxt.config.js` and send me a screenshot of the error?

**Comment by danielmoeck** [comment] 2020-02-25 20:54
Yes that sounds great @JoaoPedroAS51 
I expected the basic login to work in the way it did before just with the refresh token. 
Or did I understand this wrong?

The errorcode is basicalle 401
The header to the /users/me route sends 

Authorization: JWT undefined 

At the moment I'm using this version oft the auth-module
"@nuxtjs/auth": "github:nuxt-community/auth-module#feat/refresh",

```

auth: {
    localStorage: false,
    strategies: {
      local: {
        endpoints: {
          login: { url: '/api/v1/auth/jwt/create/', method: 'post', propertyName: 'access' },
          user: { url: '/api/v1/auth/users/me/', method: 'get', propertyName: false },
          logout: false
        },
        tokenRequired: true,
        tokenType: 'JWT'
      }

    }
  },
```

**Comment by JoaoPedroAS51** [comment] 2020-02-25 21:13
Hi @danielmoeck, I guess the problem is in your config. We refactored the config in the feat/refresh branch. You can check the docs here https://github.com/nuxt-community/auth-module/pull/361#issue-282213943

Try changing to this and tell me what happens:

```javascript
auth: {
    localStorage: false,
    strategies: {
      local: {
        _scheme: 'refresh',
        token: {
          property: 'access'
        },
        refreshToken: {
          property: 'refresh_token' // change to your refresh token property
        },
        user: false,
        endpoints: {
          login: { url: '/api/v1/auth/jwt/create/', method: 'post' },
          refresh: { url: '/api/v1/auth/jwt/refresh/', method: 'post' }, // change to your refresh token url
          user: { url: '/api/v1/auth/users/me/', method: 'get' },
          logout: false
        },
        tokenRequired: true,
        tokenType: 'JWT'
      }
    }
  }
```

**Comment by danielmoeck** [comment] 2020-02-25 21:31
Wow thank you so much for your fast reply, thats really cool!

I think everything works, I get my access and refresh token 👍 yeah!

I'm just wondering why my auth/users/me call returns "Authentication credentials were not provided.". Do you know where I could've made a mistake?

**Comment by JoaoPedroAS51** [comment] 2020-02-25 21:36
@danielmoeck I'm happy to know it worked! :)

About "Authentication credentials were not provided", try to use `tokenType: 'Bearer'`

**Comment by danielmoeck** [comment] 2020-02-25 21:39
@JoaoPedroAS51 I am very happy that you helped me! Awesome! 💯 
(it works)

Thank you so much!

**Comment by JoaoPedroAS51** [comment] 2020-02-25 21:44
@danielmoeck Yay! And if you face any other problem, don't hesitate to contact me! I'll be happy to help! ;)

**Closed** 2020-03-15 10:36 UTC
Labels: cmty:feature-request

**Comment by Salman-Kashfy** [comment] 2020-06-22 03:25
I have built a work around for this and it is working pretty good.

nuxt.config.js
`router: {
        middleware: ['refreshJWT']
    },`

refreshJWT.js
![image](https://user-images.githubusercontent.com/28507426/85245469-17106800-b461-11ea-90d4-04a3848d6e3e.png)

import jwt_decode from 'jwt-decode';
export default async function ({$auth,$axios}) {
    let token = $auth.getToken('local','token');
    if(!token) return;

    if($auth.$state.loggedIn){
        if($auth.$storage.state.strategy === 'local'){
            token = token.replace('Bearer ','');
            let decoded = jwt_decode(token);
            let expiryDate = new Date(decoded.exp*1000);
            let currentDate = new Date();
            let diffMs = expiryDate - currentDate;
            let diffMins = Math.round(((diffMs % 86400000) % 3600000) / 60000); // minutes
            if(diffMins<2){
                try{
                    let response = await $axios.post(process.env.API_URL+'/refresh');
                    await $auth.setUserToken(response.data.access_token).then(() => console.log('Token Set!'))
                }catch (e) {}
            }
            console.log(token);
            console.log(diffMins);
        }
    }
}


GitHub Repo:
https://github.com/Salman-Kashfy/Nuxt-Auth

Implementation and Demo:
https://www.youtube.com/watch?v=Zrj9vOT3-2w

**Comment by etdevs1** [comment] 2022-10-10 08:40
@iamr0man I have the same issue. How did you solve your problem?
