### ISSUE TITLE
While specifing "samesite" and "secure" cookie flags, only one applies

### ISSUE THREAD

**Issue by ghost** [nuxt-community/auth-module#1044] opened 2021-01-30 22:09 UTC
### Version
module: 5.9.0
nuxt: 2.0.0

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt configuration
```
 auth: {
    cookie: {
      options: {
        sameSite: 'Strict',
        secure: true
      }
    }
}
```

## Reproduction
Simply use above config and look at the cookie storage

#### What is expected?
Secure and SameSite cookie attributes to be marked at the same time

#### What is actually happening?
SameSite works only if Secure is not specified
If both SameSite and Secure are specified, only Secure works

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

### What is actually happening?
by specifing both "secure" and "samesite" cookie security flags, only secure applies.

Although if I just supply the "samesite" cookie without the "secure" one, the "samesite" is added.

It seems the bug is that when two cookie security attributes are added, only one is being picked.

**Comment by dargmuesli** [comment] 2021-09-08 08:07
I cannot reproduce this problem with the current version^^

**Comment by bmulholland** [comment] 2022-01-20 11:08
I'm taking @dargmuesli's comment that it's fixed at face value and closing this out. Thanks for letting us know!

**Closed by bmulholland** 2022-01-20 11:08 UTC
Labels: bug
