### ISSUE TITLE
How to set full URL?

### ISSUE THREAD

**Issue by amirakbulut** [nuxt-community/auth-module#727] opened 2020-06-11 22:15 UTC
See following situation:

```
auth: {
    redirect: {
         callback: 'http://api.mysite.com/callback',
    },
},
```

The above callback value will turn into:

`http://mysite.com/http://api.mysite.com/callback`

How to solve this?

**Comment by jurrienpiris** [comment] 2020-06-12 09:36
This seems to be happening since an update. Not sure which version. Looks like I'm also having troubles with URL's. Whenever I lock the version on 4.9.0 my issues disappear.

I'll try to reproduce this later..

**Comment by bmulholland** [comment] 2020-12-04 13:45
Closing since no repro was posted - please post a new issue if you get a repro going.

**Closed by bmulholland** 2020-12-04 13:45 UTC
